### ISSUE TITLE
Crash with REI Rendering

### ISSUE THREAD

**Issue by Bullseye55** [CafeteriaGuild/Art-of-Alchemy#40]
When looking at a model(unsure which) in Roughly Enough Items with Sodium/Indium enabled, the game crashes.
Crashlog:
https://pastebin.com/KgqEgHEt

**Comment by KyGost** [comment]
Hmm.... What makes you think it is AoA?
I haven't experienced this issue. Also the log seems to be pointing at:
```
Entry identifier: pswg:red_hangar_light
```
Not sure what mod `pswg` is but if you know, maybe try again without it?

**Comment by Bullseye55** [comment]
Checking right now. Crashed when searching "@Alch" in REI, so inferred. It'd make sense....as "light" also crashes.....yep, just crashed searching for that specific item. Testing with that disabled.....

Working without! I'll go and send this crashreport to them, then. Thank you for the assistance. Been looking forward to using Art of Alchemy quite a bit. :)

**Comment by KyGost** [comment]
Glad to hear it is figured out! :-)

Let me know how you go with AoA when you get started.

Closing as this issue seems to be resolved on AoA side.
